// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBweyAv9wvBiSDSvfuO9RMwRTXnVn3cBOg',
    appId: '1:1046853685112:web:1d4d7b7277742a8896c28d',
    messagingSenderId: '1046853685112',
    projectId: 'flutterdanfirebase',
    authDomain: 'flutterdanfirebase.firebaseapp.com',
    storageBucket: 'flutterdanfirebase.firebasestorage.app',
    measurementId: 'G-3F5FSLWGQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS4PZVQ2JRC90_73on4No-RYt5zm_JbD0',
    appId: '1:1046853685112:android:a4fb8552886476fe96c28d',
    messagingSenderId: '1046853685112',
    projectId: 'flutterdanfirebase',
    storageBucket: 'flutterdanfirebase.firebasestorage.app',
  );
}
